name: Logan Workflow

on:
  workflow_dispatch:
    inputs:
      logan_github_environment:
        description: 'The GitHub environment to use for Logan'
        required: true
        default: 'logan'
        type: string

permissions:
  contents: read

jobs:
  run-test-logan-41:
    uses: ./.github/workflows/test_logan_41.yaml
    with:
      logan_github_environment: ${{ inputs.logan_github_environment }}
    secrets:
      LOGAN_IS_NOT_HAPPY: ${{ secrets.LOGAN_IS_NOT_HAPPY }} # Here I give the permission to use the secret LOGAN_IS_NOT_HAPPY in the called workflow. If the value is set at this workflow level, the environment secret value is not used.
      LOGAN_IS_ALWAYS_HAPPY: ${{ secrets.LOGAN_IS_ALWAYS_HAPPY }} # Here I give the permission to use the secret LOGAN_IS_ALWAYS_HAPPY in the called workflow. If the value is set at this workflow level, the environment secret value is not used.
    # secrets: inherit # Here we give the permission to use any secrets in Org, Repo and Environment level.
    