name: Logan Workflow 41

on:
  workflow_call:
    inputs:
      logan_github_environment:
        description: 'The GitHub environment to use for Logan'
        required: true
        type: string
    secrets:
      LOGAN_IS_NOT_HAPPY:
        description: 'Is Logan not happy?'
        required: true
      LOGAN_IS_ALWAYS_HAPPY:
        description: 'Is Logan always happy?'
        required: true
      IS_LOGAN_HAPPY:
        description: 'Is Logan happy?'
        required: true

jobs:
  run-test-logan-41:
    runs-on: ubuntu-latest
    environment: ${{ inputs.logan_github_environment }}
    steps:
      - name: Is Logan happy?
        run: |
          echo "Logan is happy: ${{ vars.LOGAN_IS_HAPPY }}"
      - name: Is Logan sad?
        env:
          LOGAN_IS_SAD: ${{ secrets.LOGAN_IS_NOT_HAPPY }}
        run: |
          if [ "$LOGAN_IS_SAD" = "Yes" ]; then echo "Logan is sad"; else echo "Logan is not sad"; fi
      - name: Is Logan always happy?
        env:
          LOGAN_IS_ALWAYS_HAPPY: ${{ secrets.LOGAN_IS_ALWAYS_HAPPY }}
        run: |
          if [ "$LOGAN_IS_ALWAYS_HAPPY" = "No" ]; then echo "Logan is not always happy"; else echo "Logan is always happy"; fi
      - name: Check if Logan is happy or sad
        env:
          LOGAN_IS_HAPPY: ${{ secrets.IS_LOGAN_HAPPY }}
        run: |
          if [ "$LOGAN_IS_HAPPY" = "Yes" ]; then echo "Logan is happy"; else echo "Logan is sad"; fi